[build]
  command = "npm run build"
  publish = "_site"

[[headers]]
  for = "/progress/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Cache-Control = "no-store, no-cache, must-revalidate"
